import type { Course } from '@/actions/learn'

// 샘플 강좌 데이터 (DB가 비어있을 때 사용)
export const SAMPLE_COURSES: Course[] = [
    {
        id: 'sample-1',
        title: 'KIIP Level 1: Korean Culture Basics',
        description: 'Learn about Korean greetings, holidays, and daily customs. Perfect for beginners starting their Korean journey.',
        category: 'kiip',
        content_type: 'video',
        content_url: 'https://www.youtube.com/watch?v=example1',
        thumbnail_url: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=400',
        duration: '15분',
        level: 'beginner',
        created_at: new Date().toISOString(),
    },
    {
        id: 'sample-2',
        title: 'KIIP Level 2: Korean History',
        description: 'Explore the rich history of Korea from ancient times to modern era. Required for KIIP Level 2 exam.',
        category: 'kiip',
        content_type: 'text',
        content_url: '',
        thumbnail_url: 'https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?w=400',
        duration: '20분',
        level: 'beginner',
        created_at: new Date().toISOString(),
    },
    {
        id: 'sample-3',
        title: 'TOPIK Vocabulary: Essential 1000 Words',
        description: 'Master the most frequently used Korean words for TOPIK exam preparation.',
        category: 'korean',
        content_type: 'document',
        content_url: 'https://example.com/vocab.pdf',
        thumbnail_url: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400',
        duration: '자료',
        level: 'intermediate',
        created_at: new Date().toISOString(),
    },
    {
        id: 'sample-4',
        title: 'Korean Pronunciation Guide',
        description: 'Perfect your Korean pronunciation with native speaker examples and practice exercises.',
        category: 'korean',
        content_type: 'video',
        content_url: 'https://www.youtube.com/watch?v=example2',
        thumbnail_url: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=400',
        duration: '25분',
        level: 'beginner',
        created_at: new Date().toISOString(),
    },
    {
        id: 'sample-5',
        title: 'Understanding Korean Workplace Culture',
        description: 'Essential guide for working in Korean companies. Learn about hierarchy, etiquette, and communication.',
        category: 'culture',
        content_type: 'text',
        content_url: '',
        thumbnail_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
        duration: '10분',
        level: 'intermediate',
        created_at: new Date().toISOString(),
    },
    {
        id: 'sample-6',
        title: 'KIIP Level 5: Immigration & Citizenship',
        description: 'Advanced content covering Korean immigration law, visa types, and naturalization process.',
        category: 'kiip',
        content_type: 'document',
        content_url: 'https://example.com/kiip5.pdf',
        thumbnail_url: 'https://images.unsplash.com/photo-1589829545856-d10d557cf95f?w=400',
        duration: '자료',
        level: 'advanced',
        created_at: new Date().toISOString(),
    },
]
